CREATE TABLE IF NOT EXISTS labels (
  Label VARCHAR(255),
  Cartel VARCHAR(255),
  Value INT
);

LOAD DATA INFILE '/data/labels.csv'
INTO TABLE labels 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
